### ISSUE TITLE
Center and Right Text Alignment Are Switched

### ISSUE THREAD

**Issue by peternowell** [schriftgestalt/DrawBotGlyphsPlugin#10] opened 2021-10-30 15:38 UTC
In macOS Monterey, both DrawBot and Vanilla have the same issue: text alignment confuses `center` and `right` for each other. This does not appear to be an issue in the DrawBot app—only inside of Glyphs. I mention Vanilla because it seems extremely likely that it has the same bug.

### DrawBot Example:
```python
content = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. '
content = content * 3
newPage( 400, 400 )
textBox( content, (10, 10, 380, 380), align='right')
```
<img width="500" alt="Screen Shot 2021-10-30 at 11 36 35 AM" src="https://user-images.githubusercontent.com/4554849/139539731-1e493c4b-50af-45a4-9d9b-c9ddc44b5c96.png">

### Vanilla Example:
```python
from vanilla import Window, TextBox
class TextBoxDemo:
     def __init__(self):
         self.w = Window((250, 50))
         self.w.textBox = TextBox((10, 10, -10, 17), "This should be centered", alignment='center')
         self.w.open()
TextBoxDemo()
```
<img width="315" alt="Screen Shot 2021-10-30 at 11 35 41 AM" src="https://user-images.githubusercontent.com/4554849/139539737-21a7dadc-87c6-4855-9ab4-6e5b7931bf87.png">

Needless to say, it's pretty urgent that this be resolved quickly. Let me know if there's anything I can do to help troubleshoot. 🙂 Thanks!

**Comment by peternowell** [comment] 2021-11-17 01:01
@schriftgestalt @jenskutilek I would be more than happy to pay you to fix this. I know it can be difficult to justify the time required to maintain open-source software. You both have my email—let me know how I can help you get this done. 🙏

**Comment by schriftgestalt** [comment] 2021-11-17 10:00
The problem is not with DrawBot nor vanilla but with AppKit and PyobjC. Apple seems to have changed the definition of some of the constants. And this switch in not correctly handled in Pyobjc. 

I have fixed it in the Glyphs Drawbot. I’ll open an issue for vanilla.

**Comment by schriftgestalt** [comment] 2021-11-17 11:08
I fixed vanilla, too. Will probably be available shortly.

**Comment by schriftgestalt** [comment] 2021-11-17 12:01
And it is fixed in pyobjc, too.

**Closed as completed by schriftgestalt** 2021-11-17 12:01 UTC

**Comment by peternowell** [comment] 2021-11-17 17:15
Thank you SO much, @schriftgestalt! It's working correctly in Vanilla for me now, and mostly in DrawBot. `textBox()` now works correctly in DrawBot but `text()` still has the center and right alignment constants swapped. Try this code:

```python
newPage( 400, 400 )

textPosition = ( 300 , 300 )

text( 'Lorem ipsum dolor', textPosition, align='right' )

# Show a red dot where the text is postioned
fill(1,0,0)
oval( *textPosition, 10, 10 )
```

Currently renders like this:
<img width="289" alt="image" src="https://user-images.githubusercontent.com/4554849/142249140-21338f0c-85c8-49e5-9e62-eee1209b0cf1.png">


Should look like this:
<img width="329" alt="image" src="https://user-images.githubusercontent.com/4554849/142248921-6a1dcbf6-ba39-4588-bccb-95b37604070c.png">

**Comment by schriftgestalt** [comment] 2021-11-17 18:29
It works for me. Need to try on a different machine.
